### ISSUE TITLE
Omit ?page=1 on page load

### ISSUE THREAD

**Issue by adamkdean** [edge/explorer#122]
On pages such as https://test.network/block/192984 as soon as you load the querystring page=1 will be added to the URL. We should omit this when loading the page for the first time, where the pagination control hasn't been used etc.

**Comment by willgarrett64** [comment]
@adamkdean - just realised that I did this today but not quite as you asked. I just omitted it when there is only 1 page. Tomorrow I'll look at it again to remove it completely (and only add it if someone tries to enter page 0 or negative, which was the whole purpose of it in the first place)
