### ISSUE TITLE
Pending transaction weirdness

### ISSUE THREAD

**Issue by adamkdean** [edge/explorer#163]
![image](https://user-images.githubusercontent.com/1639527/170714471-60bbec19-a4fa-456d-ac00-e8ce27808153.png)

Something weird happened with pending transactions. I created 7 stake transactions one after the other. One was confirmed in block 285920 (https://test.network/block/285920), next block 285921 (https://test.network/block/285921) has the other 6. But looking at the transaction list above, they appeared as a mix of Confirmed and Pending.

**Comment by willgarrett64** [comment]
I think I'll need to check locally to see what's going on. It could be that either there is a problem with Explorer, but could also be the way Index records pending txs.
https://github.com/edge/explorer/blob/22f4ca21e66f73f6318252769a8c25213dbafad3/src/components/TransactionsTableItem.vue#L159-L163
It should only be showing "Confirmed" in status if:
- it's not "pending"
- it has < 10 confirmations
That leads me to think that the tx is actually pending, but the data is missing the pending: true flag, which is set in index.
