### ISSUE TITLE
7 day coin chart on a Monday shows only 1 day

### ISSUE THREAD

**Issue by adamkdean** [edge/explorer#219]
<img width="627" alt="image" src="https://github.com/edge/explorer/assets/1639527/f0a00e5d-04a7-46e2-b800-9133eb0998ee">

Mondays can feel like a week, but alas, we should show 7 days here

**Comment by adamkdean** [comment]
<img width="625" alt="image" src="https://github.com/edge/explorer/assets/1639527/b76fdf29-3683-4f85-b802-1d5ec7f8e13b">

Not sure about previous behaviour but today for example shows 3 days.

**Comment by willgarrett64** [comment]
Looking at 30 day chart it looks like we have data for 14th and 21st August, so that would explain why Monday only showed one value. Nothing to do with it being a Monday I would say. 
![image](https://github.com/edge/explorer/assets/74154911/7e15f815-6e39-4310-8a21-8e58d2701a91)

**Comment by adamkdean** [comment]
Oh that makes sense, we had some gaps in the data yeah, so instead of showing the last 7 data points, it shows the last 7 days, which is why we're only just seeing this. Will close ticket.
