### ISSUE TITLE
Offline nodes showing as online

### ISSUE THREAD

**Issue by adamkdean** [edge/explorer#220]
<img width="1261" alt="image" src="https://github.com/edge/explorer/assets/1639527/a242f6f9-e335-4892-89ba-6b983a68325e">

The bottom node shown above is the original Stargate which has been offline now for 3 hours. It should show as offline but still appears online. In the image below, you can see how inconsistent this appears to be:

<img width="1252" alt="image" src="https://github.com/edge/explorer/assets/1639527/83baa6a0-a3d4-4175-b480-7f84f7471531">

**Comment by adamkdean** [comment]
I think we need to make some improvements here. It could be as simple as changing the 24 hours to 1 hour for example.

Any potential issues with that @annybs?

**Comment by annybs** [comment]
I've just checked and I was right that Index self-corrected the offline nodes after 24 hours, so nothing to worry about as such.

The 24 hour window is really fairly arbitrary - it's just a window of tolerance for data loss in the event of network connectivity issues or Stargate outage. A lower value will make it more responsive to such events, but at the risk of 'flickering' if it is too low. I think an hour might be too low, but 6 hours would be reasonable.

**Comment by adamkdean** [comment]
Closed in favour of https://github.com/edge/index/issues/227
