### ISSUE TITLE
Stake index order

### ISSUE THREAD

**Issue by adamkdean** [edge/explorer#60]
Stakes on the stake index page should be ordered by Status and then Type

Active, Unlocking, Unlocked, Released
Stargate, Gateway, Host

e.g.

Active Stargate
Active Gateway
Active Host
Unlocking Stargate
Unlocking Host
Unlocked Host
Released Stargate

**Comment by annybs** [comment]
I've unassigned myself from this issue as I can't see myself working/being able to work on it any time soon.

At this juncture I am also unclear whether there is a particular need for it; we have other modes for sorting stakes using @willgarrett64's sort flags system, with default sorts presumably set in Explorer and Wallet.

I recommend closing this down if @adamkdean assents.
