### ISSUE TITLE
Tables to support sorting

### ISSUE THREAD

**Issue by adamkdean** [edge/explorer#66]
Once https://github.com/edge/index/issues/77 is done, the table headers should support sorting and this should persist through pagination. There will also need to be the ability for the table components to have default sorting params.

This will then allow https://github.com/edge/explorer/issues/60 to be completed.

**Comment by willgarrett64** [comment]
Plan of action:

- [ ] refactor stakes table and how data is fetched from index
- [ ] add sorting to stakes
- [ ] refactor txs table and how data is fetched from index
- [ ] add sorting to txs
- [ ] add sorting to blocks endpoint in index (part of https://github.com/edge/index/issues/77)
- [ ] refactor blocks table and how data is fetched from index
- [ ] add sorting to blocks

**Comment by adamkdean** [comment]
👏
